version: "3"
services:
  api:
    build: ./api
    command: npm run start
    environment:
      - HOST=localhost
      - PORT=3001
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db
  api_db:
    image: mongo:latest
    volumes:
      - mongodb_api:/data/db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend
    command: ./node_modules/.bin/serve -s build -l 3000
    restart: unless-stopped
    stdin_open: true
    tty: true
  nginx:
    image: nginx:1.23.3-alpine
    container_name: websystem-docker-alk-nginx
    ports:
      - "1234:1234"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - api
      - frontend
volumes:
  mongodb_api: