version: "3"
services:
  api:
    build: ./
    environment:
      PORT: 8080
      HOST: '0.0.0.0'
      MONGODB_URL: 'mongodb://api_db:27017/api'
    command: npm run start
    depends_on:
      - api_db
    ports:
      - "80:8080"
    volumes:
      - mongodb_api:/data/db
  api_db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_api:/data/db
volumes:
  mongodb_api:
    name: mongodb_api
