version: "3"
services:
  api:
    build: ./
    environment:
      PORT: 8080
      HOST: '0.0.0.0'
      MONGODB_URL: 'mongodb://api_db:27017/api'
    command: npm run dev
    depends_on:
      - api_db
    ports:
      - "80:8080"
    volumes:
      - .:/app
      - /app/node_modules